version: '3.9'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - "./:/var/www/html"
            - "./nginx-config:/etc/nginx/conf.d"
        networks:
            - web-db-net
    php:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - "./:/var/www/html"
        networks:
            - web-db-net
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        restart: unless-stopped
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: docker-php
        networks:
            - web-db-net

volumes:
    mysqldata:
networks:
    web-db-net: